---
  - name: Create tomcat user
    user: name=tomcat 

  - name: Download Tomcat
#    copy: src=/Users/akmi/EXCLUDE/apache-tomcat-8.0.29.tar.gz dest=/opt
    get_url: url=http://apache.hippo.nl/tomcat/tomcat-8/v8.0.30/bin/apache-tomcat-8.0.30.tar.gz dest={{ tomcat_archive }}
  
  - name: (Re-)create directory for installation files
    shell: rm -fr {{ tomcat_home }}; 
           mkdir {{ tomcat_home }}
           
  - name: Unpack archive
    command: "tar -zvxf {{tomcat_archive}} -C {{tomcat_home}} --strip 1"
    
  - name: Create directory for installation context files
    shell: rm -fr {{ tomcat_context_location }}; 
           mkdir -p {{ tomcat_context_location }}
           
  - name: Add cmd2rdf context
    template: src=cmd2rdf.xml dest={{ tomcat_context_location }}/cmd2rdf.xml
    
  - name: Add cmd2rdf context
    template: src=cmd2rdf-lda.xml dest={{ tomcat_context_location }}/cmd2rdf-lda.xml
 
  - name: Fix ownership
    file: state=directory path={{tomcat_home}} owner=tomcat group=tomcat recurse=yes
    
  - name: Create Tomcat service
    template: src=tomcat.service
            dest=/etc/systemd/system/
    
  - name: Enable Tomcat Server
    service: name=tomcat enabled=true
  
  - name: Start Tomcat Server
    service: name=tomcat   state=started
  
  - name: Clean up
    file: state=absent path={{tomcat_archive}}
